server:
  port: 8021

spring:
  application:
    name: oj-judgement-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: GROUP
  rabbitmq:
    host: localhost
    port: 15672
    password: guest
    username: guest
    publisher-confirm-type: correlated   # 开启确认回调
    publisher-returns: true              # 开启回退回调（消息未路由时）

  config:
    import[0]: nacos:oj-judgement-service-dev.yaml?group=DEFAULT_GROUP
    import[1]: nacos:oj-common-dev.yaml?group=DEFAULT_GROUP