server:
  port: 8031

spring:
  application:
    name: oj-codeSandBox-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: GROUP
  rabbitmq:
    host: localhost
    port: 15672
    password: guest
    username: guest

  config:
    import[0]: nacos:oj-common-dev.yaml?group=DEFAULT_GROUP